Traduzir distributed-workflows.asc no cap. 5
progit/progit2-pt-br pull request #46
Opened 2020-11-06 15:20 UTC by flaviovisnardifilho

Tradução do primeiro arquivo do capítulo 5: distributed-workflows.asc

2020-11-25 16:03 UTC, carlosschults requested changes
A tradução está excelente, pedi apenas algumas pequenas alterações.

2020-11-25 16:03 UTC, carlosschults commented on book/05-distributed-git/sections/distributed-workflows.asc
> +Este cenário geralmente inclui um repositório sagrado que representa o projeto ``oficial''.
Eu sugiro aqui usar "canônico" mesmo, acho que é uma familiar para desenvolvedores em vários contextos (ex: URL canônica.)

2020-11-25 16:03 UTC, carlosschults commented on book/05-distributed-git/sections/distributed-workflows.asc
> +Os coordenadores podem então adicionar seu repositório como um repositório remoto deles, testar suas mudanças localmente, mesclá-las (_merge_) nos respectivos ramos (_branch_) e publicar (_push) no r
Eu sugiro deixar branch como "branch" mesmo, ao invés de deixar como ramo e ficar definindo toda vez. Acredito que a maioria dos desenvolvedores estejam familiarizados com a palavra branch.

2021-05-26 11:53 UTC, sergiocabral commented
@carlosschults beleza?
Vi que o @flaviovisnardifilho fez o ajuste que você sugeriu. Vou dar uma força aqui e adiantar o merge, beleza?
Me avisa se eu fiz algo diferente do que pensou, porque, então, eu vou me ajustando ao processo.
Abração.

2021-05-26 11:54 UTC, merged

2021-05-26 12:15 UTC, sergiocabral commented
@flaviovisnardifilho obrigado pela ajuda... sua colaboração foi incluída no branch principal do projeto.