Tradução do Cap. 10: Introdução, plubing-porcelain, objects e refs
progit/progit2-pt-br pull request #81
Opened 2021-06-07 00:48 UTC by lucasoshiro

Olá!

Neste PR faço a tradução das 3 primeiras seções e da introdução do capítulo 10.

2021-06-08 22:06 UTC, sergiocabral commented
@lucasoshiro beleza?
Obrigado pela ajuda.
Até o fim de semana colocamos suas traduções no branch princpal.

2021-06-08 23:56 UTC, altemirpacheco commented on ch10-git-internals.asc
> +Talvez você tenha de um capítulo anterior para este, ou talvez você tenha chegado aqui depois de ler o resto do livro. De qualquer forma, aqui iremos para o funcionamento e implementação internos do
Acho que o correto seria: "Talvez você venha de um capítulo..."

2021-06-13 20:55 UTC, lucasoshiro commented on ch10-git-internals.asc
> +Talvez você tenha de um capítulo anterior para este, ou talvez você tenha chegado aqui depois de ler o resto do livro. De qualquer forma, aqui iremos para o funcionamento e implementação internos do
Vou esperar o sergio revisar, aí mando tudo de uma vez

2021-07-14 16:51 UTC, sergiocabral commented on ch10-git-internals.asc
> +Talvez você tenha de um capítulo anterior para este, ou talvez você tenha chegado aqui depois de ler o resto do livro. De qualquer forma, aqui iremos para o funcionamento e implementação internos do
Pessoal (@lucasoshiro e @altemirpacheco), desculpa. Falhei miseravelmente com vocês. Me enrolei e não cumpri com a palavra. Fazendo aqui a revisão.

2021-07-14 16:56 UTC, sergiocabral requested changes
@lucasoshiro pode fazer o ajuste que o @altemirpacheco sugeriu. Achei também que encaixa melhor "Talvez você venha de um capítulo"?

2021-07-14 19:28 UTC, altemirpacheco commented on ch10-git-internals.asc
> +Talvez você tenha de um capítulo anterior para este, ou talvez você tenha chegado aqui depois de ler o resto do livro. De qualquer forma, aqui iremos para o funcionamento e implementação internos do
Beleza @sergiocabral ! Este mês estou de férias, mas em Agosto volto pra traduzir mais alguma coisa! Vamos ver se finalizamos a tradução deste livro rsrsrs!!!

2021-07-27 01:45 UTC, lucasoshiro commented
Opa, obrigado pessoal! Corrigi esse errinho :slightly_smiling_face:

2021-09-08 16:03 UTC, sergiocabral approved these changes

2021-09-08 16:04 UTC, merged